### ISSUE TITLE
Unlinking of conda env produces error

### ISSUE THREAD

**Issue by michaelaye** [conda-forge/nb_conda_kernels-feedstock#12]
When removing a pure conda environment with only the dependencies for nb_conda_kernels, and then remove the whole environment using `conda env remove`, an error appears that seems to be related to nb_conda_kernels:

```bash
─❱❱❱ conda env remove -n nb_conda_kernels                               +6870 12:19 ❰─┘
Using Anaconda API: https://api.anaconda.org

Package plan for package removal in environment /Users/klay6683/miniconda3/envs/nb_conda_kernels:

The following packages will be REMOVED:

    appnope:                            0.1.0-py35_0
    backports.shutil_get_terminal_size: 1.0.0-py35_0     conda-forge
    ca-certificates:                    2016.9.26-0      conda-forge
    certifi:                            2016.9.26-py35_0 conda-forge
    decorator:                          4.0.10-py35_0    conda-forge
    entrypoints:                        0.2.2-py35_0     conda-forge
    ipykernel:                          4.5.0-py35_0     conda-forge
    ipython:                            5.1.0-py35_1     conda-forge
    ipython_genutils:                   0.1.0-py35_0     conda-forge
    jinja2:                             2.8-py35_1       conda-forge
    jsonschema:                         2.5.1-py35_0     conda-forge
    jupyter_client:                     4.4.0-py35_0     conda-forge
    jupyter_core:                       4.2.0-py35_0     conda-forge
    libsodium:                          1.0.10-0         conda-forge
    markupsafe:                         0.23-py35_0      conda-forge
    mistune:                            0.7.3-py35_0     conda-forge
    nb_conda_kernels:                   2.0.0-py35_0     conda-forge
    nbconvert:                          4.2.0-py35_0     conda-forge
    nbformat:                           4.1.0-py35_0     conda-forge
    ncurses:                            5.9-9            conda-forge
    notebook:                           4.2.3-py35_0     conda-forge
    openssl:                            1.0.2h-2         conda-forge
    pexpect:                            4.2.1-py35_0     conda-forge
    pickleshare:                        0.7.3-py35_0     conda-forge
    pip:                                9.0.1-py35_0     conda-forge
    prompt_toolkit:                     1.0.9-py35_0     conda-forge
    ptyprocess:                         0.5.1-py35_0     conda-forge
    pygments:                           2.1.3-py35_1     conda-forge
    python:                             3.5.2-2          conda-forge
    python.app:                         1.2-py35_4
    pyzmq:                              15.4.0-py35_0    conda-forge
    readline:                           6.2-0            conda-forge
    setuptools:                         28.8.0-py35_0    conda-forge
    simplegeneric:                      0.8.1-py35_0     conda-forge
    six:                                1.10.0-py35_0    conda-forge
    sqlite:                             3.13.0-1         conda-forge
    terminado:                          0.6-py35_0       conda-forge
    tk:                                 8.5.19-0         conda-forge
    tornado:                            4.4.2-py35_0     conda-forge
    traitlets:                          4.3.1-py35_0     conda-forge
    wcwidth:                            0.1.7-py35_0     conda-forge
    wheel:                              0.29.0-py35_0    conda-forge
    xz:                                 5.2.2-0          conda-forge
    zeromq:                             4.1.5-0          conda-forge
    zlib:                               1.2.8-3          conda-forge

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|############################################################| 100%
Traceback (most recent call last):
  File "/Users/klay6683/miniconda3/envs/nb_conda_kernels/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/klay6683/miniconda3/envs/nb_conda_kernels/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/klay6683/miniconda3/envs/nb_conda_kernels/lib/python3.5/site-packages/nb_conda_kernels/__init__.py", line 3, in <module>
    from .manager import CondaKernelSpecManager
  File "/Users/klay6683/miniconda3/envs/nb_conda_kernels/lib/python3.5/site-packages/nb_conda_kernels/manager.py", line 9, in <module>
    from jupyter_client.kernelspec import (
ImportError: No module named 'jupyter_client.kernelspec'
```

So, to reproduce:
```bash
conda create -n nb_conda_kernels python=3 -y
source activate nb_conda_kernels
conda install -y nb_conda_kernels
source deactivate
conda env remove -n nb_conda_kernels
```

Using conda 4.1.12 on macOS 10.11.6

**Comment by damianavila** [comment]
It is something known and it is related with the post-script step to enable/disable the extension.
The error is not nice to have it but it should not impact the integrity of the removal action.
