### ISSUE TITLE
Get windows and linux tests working

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/nb_conda_kernels-feedstock#3]
Windows:

```
C:\conda\conda-bld\work\nb_conda_kernels-1.0.3>IF 0 NEQ 0 EXIT /B 0 

C:\conda\conda-bld\work\nb_conda_kernels-1.0.3>CALL npm run test   || EXIT /B 1 

> nb_conda_kernels@1.0.3 test C:\conda\conda-bld\work\nb_conda_kernels-1.0.3
> python -m nose nb_conda_kernels.tests

Notebook server-info file never arrived: C:\Users\appveyor\AppData\Roaming\jupyter\runtime\nbserver-1384.json
E 
======================================================================
ERROR: nb_conda_kernels.tests.test_notebook.test_notebook
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\conda\envs\_test\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\conda\conda-bld\work\nb_conda_kernels-1.0.3\nb_conda_kernels\tests\test_notebook.py", line 195, in test_notebook
    jstest.main()
  File "C:\conda\envs\_test\lib\site-packages\notebook\jstest.py", line 631, in main
    run_jstestall(options)
  File "C:\conda\envs\_test\lib\site-packages\notebook\jstest.py", line 592, in run_jstestall
    sys.exit(1)
SystemExit: 1
-------------------- >> begin captured stdout << ---------------------

Test group: nb_conda_kernels.tests
Running tests with notebook directory 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\tmptktymc'
______________________________________________________________________
Test suite completed for system with the following information:
Python version: 2.7.11 |Continuum Analytics, Inc.| (default, Feb 16 2016, 09:58:36) [MSC v.1500 64 bit (AMD64)]
sys.executable: C:\conda\envs\_test\python.exe
Platform      : Windows-2012ServerR2-6.3.9600

Tools and libraries available at test time:
   casperjs phantomjs

Tools and libraries NOT available at test time:
   slimerjs

Status: ERROR - 1 out of 1 test groups failed (nb_conda_kernels.tests). Took 32.836s.

You may wish to rerun these, with:
  python -m notebook.jstest nb_conda_kernels.tests


--------------------- >> end captured stdout << ----------------------

Name                           Stmts   Miss  Cover 
--------------------------------------------------
nb_conda_kernels.py                2      0   100% 
nb_conda_kernels\_version.py       2      0   100% 
nb_conda_kernels\manager.py       62     49    21% 
--------------------------------------------------
TOTAL                             66     49    26%
---------------------------------------------------------------------- 
Ran 1 test in 33.001s

FAILED (errors=1) 

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\conda\\envs\\_test\\Library\\bin\\node.exe" "C:\\conda\\envs\\_test\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
npm ERR! node v4.4.1
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE
npm ERR! nb_conda_kernels@1.0.3 test: `python -m nose nb_conda_kernels.tests`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nb_conda_kernels@1.0.3 test script 'python -m nose nb_conda_kernels.tests'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nb_conda_kernels package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     python -m nose nb_conda_kernels.tests
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nb_conda_kernels
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nb_conda_kernels
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\conda\conda-bld\work\nb_conda_kernels-1.0.3\npm-debug.log
TESTS FAILED: nb_conda_kernels-1.0.3-py27_0
Command exited with code 1
```

Linux: as with https://github.com/conda-forge/nbpresent-feedstock/issues/3

**Comment by bollwyvl** [comment]
Also on windows:
```
:\conda\conda-bld\work\nb_conda_kernels-1.0.3>IF 0 NEQ 0 EXIT /B 0 
 
C:\conda\conda-bld\work\nb_conda_kernels-1.0.3>CALL npm run test   || EXIT /B 1 
 
> nb_conda_kernels@1.0.3 test C:\conda\conda-bld\work\nb_conda_kernels-1.0.3
> python -m nose nb_conda_kernels.tests
 
Test file: C:\conda\conda-bld\work\nb_conda_kernels-1.0.3\nb_conda_kernels\tests\js\test_notebook_basic.js
Timeout for http://localhost:8888/a@b/
Is the notebook server running?
FAIL ".list_item" still did not exist in 10000ms
#    type: uncaughtError
#    file: C:\conda\conda-bld\work\nb_conda_kernels-1.0.3\nb_conda_kernels\tests\js\test_notebook_basic.js
#    error: ".list_item" still did not exist in 10000ms
 
#    stack: not provided
Test file: C:\conda\conda-
```

**Comment by mcg1969** [comment]
We're testing on all platforms now.
